services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_cerebro
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      # Ces variables permettent à n8n de lire ton .env pour les utiliser dans les expressions {{ $env.VAR }}
    volumes:
      - n8n_data:/home/node/.local/share/n8n

volumes:
  n8n_data:
    driver: local